name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Angelo270204
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "generate snake contribution graph"
          add: "dist"
          push: origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
